const countryToISO2: Record<string, string> = {
  "Argentina": "ar",
  "Algeria": "dz",
  "Australia": "au",
  "Austria": "at",
  "Belgium": "be",
  "Bolivia": "bo",
  "Bosnia & Herzegovina": "ba",
  "Brazil": "br",
  "Bulgaria": "bg",
  "Canada": "ca",
  "Cape Verde": "cv",
  "Chile": "cl",
  "China": "cn",
  "Colombia": "co",
  "Costa Rica": "cr",
  "Croatia": "hr",
  "Curacao": "cw",
  "Cyprus": "cy",
  "Czech Republic": "cz",
  "Denmark": "dk",
  "Ecuador": "ec",
  "Egypt": "eg",
  "El Salvador": "sv",
  "England": "gb-eng",
  "Estonia": "ee",
  "Finland": "fi",
  "France": "fr",
  "Germany": "de",
  "Ghana": "gh",
  "Greece": "gr",
  "Guatemala": "gt",
  "Haiti": "ht",
  "Honduras": "hn",
  "Hungary": "hu",
  "Iceland": "is",
  "India": "in",
  "Indonesia": "id",
  "Iran": "ir",
  "Iraq": "iq",
  "Ireland": "ie",
  "Israel": "il",
  "Italy": "it",
  "Ivory Coast": "ci",
  "Jamaica": "jm",
  "Japan": "jp",
  "Jordan": "jo",
  "Kazakhstan": "kz",
  "Kenya": "ke",
  "Kuwait": "kw",
  "Latvia": "lv",
  "Lebanon": "lb",
  "Libya": "ly",
  "Lithuania": "lt",
  "Luxembourg": "lu",
  "Malaysia": "my",
  "Malta": "mt",
  "Mexico": "mx",
  "Morocco": "ma",
  "Netherlands": "nl",
  "New Zealand": "nz",
  "Nigeria": "ng",
  "Northern Ireland": "gb-nir",
  "Norway": "no",
  "Oman": "om",
  "Panama": "pa",
  "Paraguay": "py",
  "Peru": "pe",
  "Philippines": "ph",
  "Poland": "pl",
  "Portugal": "pt",
  "Qatar": "qa",
  "Romania": "ro",
  "Russia": "ru",
  "Saudi Arabia": "sa",
  "Scotland": "gb-sct",
  "Senegal": "sn",
  "Serbia": "rs",
  "Singapore": "sg",
  "Slovakia": "sk",
  "Slovenia": "si",
  "South Africa": "za",
  "South Korea": "kr",
  "Spain": "es",
  "Sweden": "se",
  "Switzerland": "ch",
  "Thailand": "th",
  "Tunisia": "tn",
  "Turkey": "tr",
  "UAE": "ae",
  "Ukraine": "ua",
  "United Arab Emirates": "ae",
  "United Kingdom": "gb",
  "Uruguay": "uy",
  "USA": "us",
  "Venezuela": "ve",
  "Vietnam": "vn",
  "Wales": "gb-wls",
  "Gibraltar": "gi",
  /** UEFA / European club competitions (flagcdn EU) */
  "Europe": "eu",
  "UEFA": "eu",
  "intl": "",
};

export function getCountryISO2(countryName: string | undefined): string | null {
  if (!countryName) return null;
  return countryToISO2[countryName] || null;
}

export function getFlagUrl(iso2: string): string {
  return `https://flagcdn.com/w20/${iso2}.png`;
}

export function getCountryFlagUrl(countryName: string | undefined): string | null {
  const iso2 = getCountryISO2(countryName);
  if (!iso2) return null;
  return getFlagUrl(iso2);
}
