export function normalizeKey(input: string): string {
  return (input ?? "")
    .toLowerCase()
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/&/g, " and ")
    .replace(/[^\w\s]/g, " ")
    .replace(/\s+/g, " ");
}

export const TEAM_PILL_DISPLAY_BY_SLUG: Record<string, string> = {
  // Premier League
  "arsenal": "Arsenal",
  "aston-villa": "Aston Villa",
  "bournemouth": "Bournemouth",
  "brentford": "Brentford",
  "brighton": "Brighton",
  "burnley": "Burnley",
  "chelsea": "Chelsea",
  "crystal-palace": "Crystal Palace",
  "everton": "Everton",
  "fulham": "Fulham",
  "leeds": "Leeds",
  "liverpool": "Liverpool",
  "manchester-city": "Man City",
  "manchester-united": "Man Utd",
  "manchester-utd": "Man Utd",
  "newcastle-united": "Newcastle",
  "newcastle": "Newcastle",
  "nottingham-forest": "Nott'm Forest",
  "nottingham": "Nott'm Forest",
  "sunderland": "Sunderland",
  "tottenham-hotspur": "Tottenham",
  "tottenham": "Tottenham",
  "west-ham-united": "West Ham",
  "west-ham": "West Ham",
  "wolverhampton-wanderers": "Wolves",
  "wolves": "Wolves",

  // Championship
  "birmingham-city": "Birmingham",
  "birmingham": "Birmingham",
  "blackburn-rovers": "Blackburn",
  "bristol-city": "Bristol City",
  "charlton-athletic": "Charlton",
  "coventry-city": "Coventry",
  "coventry": "Coventry",
  "derby-county": "Derby",
  "hull-city": "Hull",
  "ipswich-town": "Ipswich",
  "ipswich": "Ipswich",
  "leicester-city": "Leicester",
  "leicester": "Leicester",
  "middlesbrough": "Middlesbrough",
  "millwall": "Millwall",
  "norwich-city": "Norwich",
  "norwich": "Norwich",
  "oxford-united": "Oxford Utd",
  "portsmouth": "Portsmouth",
  "preston-north-end": "Preston",
  "queens-park-rangers": "QPR",
  "sheffield-united": "Sheffield Utd",
  "sheffield-utd": "Sheffield Utd",
  "sheffield-wednesday": "Sheffield Wed",
  "sheffield-wed": "Sheffield Wed",
  "southampton": "Southampton",
  "stoke-city": "Stoke",
  "swansea-city": "Swansea",
  "watford": "Watford",
  "west-bromwich-albion": "West Brom",
  "wrexham": "Wrexham",

  // League One
  "afc-wimbledon": "AFC Wimbledon",
  "barnsley": "Barnsley",
  "blackpool": "Blackpool",
  "bolton-wanderers": "Bolton",
  "bradford-city": "Bradford",
  "burton-albion": "Burton",
  "cardiff-city": "Cardiff",
  "doncaster-rovers": "Doncaster",
  "exeter-city": "Exeter",
  "huddersfield-town": "Huddersfield",
  "leyton-orient": "Leyton Orient",
  "lincoln-city": "Lincoln",
  "luton-town": "Luton",
  "mansfield-town": "Mansfield",
  "northampton-town": "Northampton",
  "peterborough-united": "Peterborough",
  "plymouth-argyle": "Plymouth",
  "port-vale": "Port Vale",
  "reading": "Reading",
  "rotherham-united": "Rotherham",
  "stevenage": "Stevenage",
  "stockport-county": "Stockport",
  "wigan-athletic": "Wigan",
  "wycombe-wanderers": "Wycombe",

  // League Two
  "accrington-stanley": "Accrington",
  "barnet": "Barnet",
  "barrow": "Barrow",
  "bristol-rovers": "Bristol Rovers",
  "bromley": "Bromley",
  "cambridge-united": "Cambridge Utd",
  "cheltenham-town": "Cheltenham",
  "chesterfield": "Chesterfield",
  "colchester-united": "Colchester",
  "crawley-town": "Crawley",
  "crewe-alexandra": "Crewe",
  "fleetwood-town": "Fleetwood",
  "gillingham": "Gillingham",
  "grimsby-town": "Grimsby",
  "harrogate-town": "Harrogate",
  "milton-keynes-dons": "MK Dons",
  "newport-county": "Newport",
  "notts-county": "Notts County",
  "oldham-athletic": "Oldham",
  "salford-city": "Salford",
  "shrewsbury-town": "Shrewsbury",
  "swindon-town": "Swindon",
  "tranmere-rovers": "Tranmere",
  "walsall": "Walsall",

  // National League
  "aldershot-town": "Aldershot",
  "altrincham": "Altrincham",
  "boreham-wood": "Boreham Wood",
  "boston-united": "Boston Utd",
  "brackley-town": "Brackley",
  "braintree-town": "Braintree",
  "carlisle-united": "Carlisle",
  "eastleigh": "Eastleigh",
  "halifax-town": "Halifax",
  "forest-green-rovers": "Forest Green",
  "gateshead": "Gateshead",
  "hartlepool-united": "Hartlepool",
  "morecambe": "Morecambe",
  "rochdale": "Rochdale",
  "scunthorpe-united": "Scunthorpe",
  "solihull-moors": "Solihull Moors",
  "southend-united": "Southend",
  "sutton-united": "Sutton",
  "tamworth": "Tamworth",
  "truro-city": "Truro",
  "wealdstone": "Wealdstone",
  "woking": "Woking",
  "yeovil-town": "Yeovil",
  "york-city": "York",

  // Scotland
  "aberdeen": "Aberdeen",
  "celtic": "Celtic",
  "dundee": "Dundee",
  "dundee-united": "Dundee Utd",
  "falkirk": "Falkirk",
  "heart-of-midlothian": "Hearts",
  "hibernian": "Hibernian",
  "kilmarnock": "Kilmarnock",
  "livingston": "Livingston",
  "motherwell": "Motherwell",
  "rangers": "Rangers",
  "st-mirren": "St Mirren",

  // Scottish Championship
  "airdrieonians": "Airdrieonians",
  "arbroath": "Arbroath",
  "ayr-united": "Ayr Utd",
  "dunfermline-athletic": "Dunfermline",
  "greenock-morton": "Morton",
  "partick-thistle": "Partick",
  "queens-park": "Queen's Park",
  "raith-rovers": "Raith",
  "ross-county": "Ross County",
  "st-johnstone": "St Johnstone",

  // Scottish League One
  "alloa-athletic": "Alloa",
  "cove-rangers": "Cove Rangers",
  "east-fife": "East Fife",
  "hamilton-academical": "Hamilton",
  "inverness-caledonian-thistle": "Inverness CT",
  "kelty-hearts": "Kelty Hearts",
  "montrose": "Montrose",
  "peterhead": "Peterhead",
  "queen-of-the-south": "Queen of the South",
  "stenhousemuir": "Stenhousemuir",

  // Scottish League Two
  "annan-athletic": "Annan",
  "clyde": "Clyde",
  "dumbarton": "Dumbarton",
  "east-kilbride": "East Kilbride",
  "edinburgh-city": "Edinburgh City",
  "elgin-city": "Elgin",
  "forfar-athletic": "Forfar",
  "stirling-albion": "Stirling Albion",
  "stranraer": "Stranraer",
  "spartans": "Spartans",

  // La Liga
  "athletic-club": "Athletic Club",
  "atletico-madrid": "Atletico Madrid",
  "osasuna": "Osasuna",
  "alaves": "Alaves",
  "elche": "Elche",
  "barcelona": "Barcelona",
  "getafe": "Getafe",
  "girona": "Girona",
  "levante": "Levante",
  "rayo-vallecano": "Rayo Vallecano",
  "celta-vigo": "Celta Vigo",
  "espanyol": "Espanyol",
  "mallorca": "Mallorca",
  "real-betis": "Real Betis",
  "real-madrid": "Real Madrid",
  "real-oviedo": "Real Oviedo",
  "real-sociedad": "Real Sociedad",
  "sevilla": "Sevilla",
  "valencia": "Valencia",
  "villarreal": "Villarreal",

  // Serie A
  "atalanta": "Atalanta",
  "bologna": "Bologna",
  "cagliari": "Cagliari",
  "como": "Como",
  "cremonese": "Cremonese",
  "fiorentina": "Fiorentina",
  "genoa": "Genoa",
  "verona": "Verona",
  "inter": "Inter",
  "juventus": "Juventus",
  "lazio": "Lazio",
  "lecce": "Lecce",
  "milan": "Milan",
  "napoli": "Napoli",
  "parma": "Parma",
  "pisa": "Pisa",
  "roma": "Roma",
  "sassuolo": "Sassuolo",
  "torino": "Torino",
  "udinese": "Udinese",

  // Bundesliga
  "bayern-munich": "Bayern Munich",
  "bayer-leverkusen": "Leverkusen",
  "eintracht-frankfurt": "Frankfurt",
  "borussia-dortmund": "Dortmund",
  "freiburg": "Freiburg",
  "mainz": "Mainz",
  "rb-leipzig": "RB Leipzig",
  "werder-bremen": "Werder Bremen",
  "stuttgart": "Stuttgart",
  "borussia-monchengladbach": "M'gladbach",
  "wolfsburg": "Wolfsburg",
  "augsburg": "Augsburg",
  "union-berlin": "Union Berlin",
  "st-pauli": "St Pauli",
  "hoffenheim": "Hoffenheim",
  "heidenheim": "Heidenheim",
  "cologne": "Cologne",
  "hamburg": "Hamburg",

  // Ligue 1
  "angers": "Angers",
  "auxerre": "Auxerre",
  "brest": "Brest",
  "le-havre": "Havre",
  "lens": "Lens",
  "lille": "Lille",
  "lorient": "Lorient",
  "lyon": "Lyon",
  "marseille": "Marseille",
  "metz": "Metz",
  "monaco": "Monaco",
  "nantes": "Nantes",
  "nice": "Nice",
  "paris-fc": "Paris FC",
  "paris-saint-germain": "PSG",
  "paris-st-germain": "PSG",
  "rennes": "Rennes",
  "strasbourg": "Strasbourg",
  "toulouse": "Toulouse",
};

const TEAM_VARIANT_DISPLAY_PAIRS: Array<[string, string]> = [
  ["Manchester United", "Man Utd"],
  ["Manchester City", "Man City"],
  ["Nottingham Forest", "Nott'm Forest"],
  ["Wolverhampton Wanderers", "Wolves"],
  ["Brighton & Hove Albion", "Brighton"],
  ["Paris Saint-Germain", "PSG"],
  ["Paris St Germain", "PSG"],
  ["Paris St-Germain", "PSG"],
  ["Le Havre", "Havre"],
  ["Le Havre AC", "Havre"],
];

export const TEAM_PILL_DISPLAY_BY_NAME_NORM: Record<string, string> = TEAM_VARIANT_DISPLAY_PAIRS.reduce(
  (acc, [name, display]) => {
    acc[normalizeKey(name)] = display;
    return acc;
  },
  {} as Record<string, string>,
);

const COMP_VARIANT_DISPLAY_PAIRS: Array<[string, string]> = [
  ["Premier League", "Premier League"],
  ["Championship", "Championship"],
  ["League One", "League One"],
  ["League Two", "League Two"],
  ["League 1", "League One"],
  ["League 2", "League Two"],
  ["National League", "National League"],
  ["FA Cup", "FA Cup"],
  ["EFL Cup", "EFL Cup"],
  ["Scottish Premiership", "Scottish Premiership"],
  ["Scottish Championship", "Scottish Championship"],
  ["Scottish League One", "Scottish League One"],
  ["Scottish League Two", "Scottish League Two"],
  ["La Liga", "La Liga"],
  ["Serie A", "Serie A"],
  ["Bundesliga", "Bundesliga"],
  ["Ligue 1", "Ligue 1"],
  ["UEFA Champions League", "Champions League"],
  ["UEFA Europa League", "Europa League"],
  ["UEFA Europa Conference League", "Conference League"],
];

export const COMP_PILL_DISPLAY_BY_NAME_NORM: Record<string, string> = COMP_VARIANT_DISPLAY_PAIRS.reduce(
  (acc, [name, display]) => {
    acc[normalizeKey(name)] = display;
    return acc;
  },
  {} as Record<string, string>,
);
